name: sentinel

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install graphviz
        run: sudo apt-get install graphviz
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
      - name: Install dependencies
        run: pip install -e ".[dev]"
      - name: Lint code
        run: black --check .
      - name: Run tests
        run: pytest --cov=sentinel --cov-report=term-missing --durations=5
  run:
    name: Run experiments
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install graphviz
        run: sudo apt-get install graphviz
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
      - name: Install dependencies
        run: pip install -e ".[dev]"
      - name: Fit models
        run: make results
